apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: signup
    component: prometheus
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: signup
      component: prometheus
  template:
    metadata:
      labels:
        app: signup
        component: prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.13.1
          name: prometheus
          ports:
            - containerPort: 9090
              name: prometheus
      nodeSelector:
        beta.kubernetes.io/os: linux
