apiVersion: v1
kind: Service
metadata:
  name: homepage
spec:
  ports:
    - port: 8081
      targetPort: 80
      name: homepage
  selector:
    app: signup
    component: homepage
  type: LoadBalancer