apiVersion: v1
kind: Service
metadata:
  name: signup-web
spec:
  selector:
    app: signup
    component: web
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signup-web
spec:
  selector:
    matchLabels:
      app: signup
      component: web
  template:
    metadata:
      labels:
        app: signup
        component: web
    spec:
      containers:
        - image: dak4dotnet/signup-web-core:linux
          name: signup-web
          env:
            - name: ReferenceDataApi__Url
              value: "http://reference-data-api/api"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: logs
              mountPath: /logs
            - name: secrets
              mountPath: "/app/secrets"
              readOnly: true
        - image: alpine:3.11
          name: signup-web-logs
          command: ["tail"]
          args: ["-n", "1", "-F", "/logs/signup-web.log"]
          volumeMounts:
            - name: logs
              mountPath: /logs
              readOnly: true
      volumes:
        - name: logs
          emptyDir: {}
        - name: secrets
          secret:
            secretName: signup-web-secret
      nodeSelector:
        beta.kubernetes.io/os: linux
