apiVersion: v1
kind: Secret
metadata:
  name: signup-web-secret
  labels:
    dak4dotnet: '20.05'
type: Opaque
stringData:
  secret.json: |-
    {
      "ConnectionStrings": {
        "SignUpDb": "Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!"
      }
    }