name: Linux Kubernets image builds

on:
  push:
    paths:
      - ".github/workflows/build-k8s.yaml"
      - "k8s/**"
  schedule:
    - cron: "0 0-7 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build and push K8s samples
        working-directory: ci
        run: |
          docker login -u $USER -p $TOKEN
          docker-compose -f docker-compose-build-k8s.yml build
          docker-compose -f docker-compose-build-k8s.yml push
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}