name: Linux image build

on:
  push:
    paths:
      - ".github/**"
      - "ci/**"
      - "docker/**"
      - "src/**"
  schedule:
    - cron: "0 0-7 * * *"

jobs:
  buildx:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Install buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build and push images
        working-directory: ./ci
        run: |
          docker login -u $USER -p $TOKEN
          docker buildx bake \
           -f docker-compose-build-linux.yml \
           --push
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
