name: Linux image build

on: push

jobs:
  buildx:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
      - name: Build and push images
        working-directory: ./ci
        run: |
          docker login -u $USER -p $TOKEN
          docker-compose -f docker-compose-build-windows.yaml build
          docker-compose -f docker-compose-build-windows.yaml push
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
